apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:  # 배포된 어플리케이션을 API 서버에서 찾아 Metric을 수집하기 위한 어노테이션 설정
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: nginx
        image: sysnet4admin/nginx-status
        ports:
        - containerPort: 80

# 어노테이션으로 메트릭 수집하기
# 프로메테우스는 어노테이션을 이용해 수집 대상을 판별하고 경로를 재조합함. 어노테이션으로 경로를 노출하고 메트릭을 수집하는 과정은 아래와 같다.
# 1. 프로메테우스에 메트릭을 공개하려는 어플리케이션은 어노테이션이 매티패스트에 추가되어있어햐 한다. 어노테이션에 추가되는 문구는 "prometheus.io/"로 시작한다.
# 2. 작성된 매니페스트를 쿠버네티스 클러스터에 배포해 어노테이션을 포함한 정보를 API 서버에 등록한다.
# 3. 프로메테우스 서버가 prometheus.io/로 시작하는 어노테이션 정보를 기준으로 대상의 주소를 만든다.
# 4. 프로메테우스 서버가 어노테이션을 기준으로 만든 대상의 주소로 요청을 보내 메트릭 데이터를 수집한다.
